version: 3

env:
  DOPPLER_PROJECT: narb
  DOPPLER_CONFIG: nonprod

tasks:
  pretty:
    desc: Uses the Prettier CLI tool to format the codebase.
    aliases:
      - p
      - format
      - fmt
    cmds:
      - prettier --write .

  build:
    desc: Builds the project by transpiling the codebase into JavaScript.
    aliases:
      - bd
    cmds:
      - docker-compose build

  clean:
    desc: Deletes the build output directory any installed dependencies and any generated files.
    aliases:
      - c
    cmds:
      - rm -rf dist node_modules package-lock.json yarn.lock pnpm-lock.yaml

  push:
    desc: Push any git changes and tags to the remote repository.
    aliases:
      - gp
    deps:
      - build
    cmds:
      - git push
      - git push --tags

  secrets:
    desc: Syncs the secrets from Doppler to the local environment.
    aliases:
      - s
    cmds:
      - doppler secrets download --no-file --format env -p {{ .DOPPLER_PROJECT }} -c {{ .DOPPLER_CONFIG }} > .env

  restart:
    aliases: [r]
    desc: Rebuilds and restarts the project.
    cmds:
      - task build
      - docker-compose down
      - task secrets
      - docker-compose up -d
      - docker-compose logs -f
